/* eslint-disable @next/next/no-img-element */
import {
	Navbar,
	CoinSidebar,
	CoinOverview,
	CoinExchanges,
	CoinMarkets,
} from '@/home/home.components/home.components';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';

export const getStaticProps = async (context) => {
	let { params } = context;
	const res = await fetch(
		`${process.env.REMOTE_API_URL}/coin/${params.coinId}?${process.env.COIN_API_KEY}`
	);
	const resData = await res.json();
	if (res.success !== 200) {
		return {
			props: {
				explore: false,
			},
		};
	} else {
		return {
			props: {
				explore: resData.data.coin,
			},
		};
	}
};

export async function getStaticPaths() {
	const res = await fetch(
		`${process.env.REMOTE_API_URL}/coins/?${process.env.COIN_API_KEY}`
	);
	const coinData = await res.json();
	if (res.status !== 'success') {
		return {
			paths: [{ params: { coinId: 'null' } }],
			fallback: true,
		};
	} else {
		const pathData = coinData.data.coins.map((coin) => {
			return {
				params: { coinId: `${coin.uuid}` },
			};
		});
		return {
			paths: [...pathData],
			fallback: true,
		};
	}
}

const AboutCoin = ({ explore }) => {
	const [openTab, setOpenTab] = useState('Overview');

	const router = useRouter();
	if (router.isFallback) {
		return 'Loading...';
	}

	!explore && console.log('Data fetching error!');

	const tabs = [
		{ name: 'Overview', badge: '', content: <CoinOverview /> },
		{
			name: 'Exchanges',
			badge: (
				<span className='bg-blue-100 text-blue-800 text-xs font-semibold ml-1 px-1.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800'>
					{explore.numberOfExchanges}
				</span>
			),
			content: <CoinExchanges />,
		},
		{
			name: 'Markets',
			badge: (
				<span className='bg-blue-100 text-blue-800 text-xs font-semibold ml-1 px-1.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800'>
					{explore.numberOfMarkets}
				</span>
			),
			content: <CoinMarkets />,
		},
	];

	const TopBar = ({ icon, name, symbol, price, color, rank }) => {
		return (
			<>
				<div className='flex space-x-2'>
					<img src={icon} alt='' width={35} height={10} />
					<h1 className='text-3xl'>
						{name}
						<span style={{ color: color }}> {symbol}</span>
					</h1>
					<span className='text-[0.8rem] text-slate-400'>#{rank}</span>
				</div>
				<div>
					<h3 className='text-2xl'>
						$ {new Intl.NumberFormat().format(price)}
					</h3>
				</div>
			</>
		);
	};

	return (
		<>
			<Head>
				<title>Explore | CoinBoat</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			{explore && (
				<>
					<div className='flex flex-col md:flex-row flex-1 md:mx-3 my-6'>
						<main className='flex-1 md:order-1 w-full order-2'>
							<div className='bg-white shadow-sm rounded-md md:mr-1 py-5 px-4'>
								<div className='flex justify-between items-center mb-4'>
									<TopBar
										name={explore.name}
										icon={explore.iconUrl}
										symbol={explore.symbol}
										price={explore.price}
										color={explore.color}
										rank={explore.rank}
									/>
								</div>
								<hr />
								<div className='w-full'>
									<ul className='flex w-full justify-center -mb-px text-sm font-medium text-center border-b-[1.3px]'>
										{tabs.map((tab, index) => (
											<li key={tab.name}>
												<a
													href={tab.link}
													onClick={() => setOpenTab(tab.name)}
													className={`${
														openTab === tab.name
															? 'border-blue-500 border-b-[2px]'
															: ''
													} inline-block p-4 rounded-t-lg`}
												>
													{tab.name} {tab.badge}
												</a>
											</li>
										))}
									</ul>
									<div className='p-3 mt-6'>
										{tabs.map((tab) => (
											<div
												key={tab.name}
												className={tab.name === openTab ? 'block' : 'hidden'}
											>
												{tab.content}
											</div>
										))}
									</div>
								</div>
							</div>
							<div>
								<p>
									Bitcoin is the first digital currency that allows users to
									send and receive money, without the interference of a central
									bank or government. Instead, a network of thousands of peers
									is controlling the transactions; a decentralized system.
								</p>
								\n\n<h3>Why does bitcoin have value?</h3>\n\n
								<p>
									Bitcoin&rsquo;s useful qualities (decentralized, borderless,
									secure) aren&rsquo;t the only reason the coin is worth so
									much. Due to its scarcity (and it&rsquo;s hard to produce),
									Bitcoin is often nicknamed &lsquo;Digital Gold&rsquo;, in
									reference to &lsquo;classic&rsquo; physical gold. Like gold,
									Bitcoin also has a finite supply of coins available; there
									will only ever be 21 million bitcoin. And now you know why the
									creation of new bitcoins is also called mining.
								</p>
								\n\n<h3>No inflation in bitcoin</h3>\n\n
								<p>
									Bitcoin was invented in response to a few concerns the
									inventor(s) had, such as inflation. Its supply is limited, so
									one cannot just devalue the currency by printing more, as
									governments often do with fiat currencies (USD, EUR, etc.).
								</p>
								\n\n
								<p>
									As people look for alternative places to keep their money
									rather than losing value in a negative interest rate account,
									Bitcoin becomes more appealing. Big global companies, such as
									Tesla and MicroStrategy already purchased serious amounts of
									Bitcoin. And it&#39;s only a matter of time that other
									companies will follow. This also ensures that the value
									remains or continues to increase.
								</p>
								\n\n<h3>Who built Bitcoin</h3>\n\n
								<p>
									In 2008, Bitcoin was invented by an anonymous person or group
									named Satoshi Nakamoto. In 2009, Bitcoin was released as
									open-source software. Nakamoto&rsquo;s real identity is still
									unknown, although there are many theories about who it might
									be. Decentralization is one of Bitcoin&rsquo;s most important
									principles, and that&rsquo;s why this anonymity is perfectly
									in line.
								</p>
								\n\n<h3>The technology of Bitcoin</h3>\n\n
								<p>
									The Bitcoin blockchain is a database, the so-called
									&lsquo;ledger&rsquo;, that consists of bitcoin transaction
									records. For new transactions to be added to the ledger, the
									nodes must agree that the transaction is real and valid. The
									blockchain is public and contains records of all the
									transactions taking place.
								</p>
								\n\n<h3>How to buy bitcoin?</h3>\n\n
								<p>Continue reading on how to buy your first bitcoin</p>
							</div>
						</main>
						<aside className='bg-white w-full md:w-80 shadow-sm rounded-md md:ml-1 px-4 py-5 md:order-2 order-1 sticky h-screen top-[4.5em]'>
							<CoinSidebar />
						</aside>
					</div>
				</>
			)}
		</>
	);
};

export default AboutCoin;
