import Head from 'next/head';
import { Navbar, Stats, Explore, Footer } from '@/components/index';
import { useSelector } from 'react-redux';

const ExploreCoins = () => {
	return (
		<>
			<Head>
				<title>Explore | CoinBoat</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/images/brand/favicon.ico' />
			</Head>
			<Stats />
			<Navbar />
			<Explore />
			<Footer />
		</>
	);
};

export default ExploreCoins;
