import Head from 'next/head';
import Header from '@/home/Header';

export default function Home() {
	return (
		<>
			<Head>
				<title>CoinBoat | The Coin Market</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
		</>
	);
}
