import React from 'react';
import jwt from 'jsonwebtoken';
import Head from 'next/head';

export async function getServerSideProps(context) {
	const { req } = context;
	const { token } = req.cookies || {};

	if (!token) {
		return {
			redirect: {
				destination: '/account/login',
				permanent: false,
			},
		};
	}

	try {
		const status = jwt.verify(token, process.env.SALT_FOR_CHIPS);
		return {
			props: {
				userId: status,
			},
		};
	} catch (error) {
		return {
			redirect: {
				destination: '/account/login',
				permanent: false,
			},
		};
	}
}

const Dashboard = ({ userId }) => {
	console.log(new Date(userId.exp * 1000));
	return (
		<>
			<Head>
				<title>Dashboard | CoinBoat</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/images/brand/favicon.ico' />
			</Head>
		</>
	);
};

export default Dashboard;
