import React from 'react';
import Head from 'next/head';

const Dashboard = () => {
	// let loginExpiry = new Date(userId.exp * 1000).getMinutes();
	// if (loginExpiry === 1) {
	// 	Cookies.remove('token');
	// }
	return (
		<>
			<Head>
				<title>Dashboard | CoinBoat</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/images/brand/favicon.ico' />
			</Head>
		</>
	);
};

export default Dashboard;
